### PR TITLE
[SE-3067] Add Python 3 support and update zip

### PR DESCRIPTION
**Pull request by toxinu**
This pull request is about updating vectordraw.py to Python 3.

**Jira tickets**

- [SE-3067](https://tasks.opencraft.com/browse/SE-3067)

**Testing instructions**

Since this module is a lot outdated, all examples are pointing to dead links (not updated static files), so it is kinda complicated to test it. I think a simple review of the changes is enough.

**Reviewers**

- @mtyaka 
- @s0b0lev

### CODE REVIEW

**Comment by s0b0lev** [comment]
@toxinu :+1:

- [x] I read through the code
- [x] Follow testing instruction. (Also run tests locally in python 3 environment)

**Comment by toxinu** [comment]
@s0b0lev I just realized that I added a third party library (`six`) and it is still working. Maybe it uses the one from `edx-platform`. Should be safer to not use it maybe, what's your thought?

**Comment by s0b0lev** [comment]
> @s0b0lev I just realized that I added a third party library (`six`) and it is still working. Maybe it uses the one from `edx-platform`. Should be safer to not use it maybe, what's your thought?

I thought it will run in some pre-existing virtualenv (because this repository doesn't have requirements.txt). So yeh, I install only `six` manually to the empty python 3+ virtualenv. 

So I think we should at least update `Installation` section of the README here. I don't think that it will be good idea to vendor package six into zip archive :thinking: 

What do you think @toxinu?

**Review by nizarmah — APPROVED** [review]
:+1: I just wanted to make sure that the changes were done to the `python_lib.zip` too. And I see they were done. :slightly_smiling_face:

**Comment by nizarmah** [comment]
@toxinu @s0b0lev Sorry to barge in like that, but I think having `six` is a good idea. The dependency is already installed with the edX platform. 

It is important to keep backwards support, for now, because there are no releases or tags and the repository is used on older releases that require Python 2.7, such as Ironwood.
Therefore, anyone on Ironwood that is using this repository is cloning it from the `master` branch. So, if we remove Python 2.7 support, it won't work for releases before Juniper.

Once most of the people using the edX platform are off of Ironwood, we can remove backwards support (aka `six`).

@toxinu please make sure you tag the commit once you merge, so that users start cloning the repository by the tag instead of the branch.

**Comment by toxinu** [comment]
@s0b0lev @nizarmah I agree that we should keep Python 2/3 compat but I prefer to not use `six` here since it is a very simple thing to handle, so that we don't rely on `edx-platform` dependency. Let me know if I can merge it, so I can put a new tag.

**Review by nizarmah — APPROVED** [review]
:+1:

@toxinu this is ready to merge

Awesome job with the changes, you're right, it is better not to use a package when you can handle the changes yourself :slightly_smiling_face: 

- [x] I tested this: 
  - I ran the `test_vectordraw.py` and made sure all tests pass
  - I made sure that the changes were also applied inside the ZIP `python_lib.zip`
- [x] I read through the code

---

If you have time, there's a deprecation warning on the tests that needs to be changed:
```
test_vectordraw.py:166: DeprecationWarning: Please use assertEqual instead.
  self.assertFails(vd.check_angle(self.check(315, 0.1), vectors), errmsg)
```

**Pull request merged**
