### PR TITLE
Daniel

### PR DESCRIPTION
**Pull request by dseaton**
@antoviaque @mtyaka I have added two new examples for Physics. Instructors would like to have students directly measure properties of a given image. We can use the segment tool for this, but need to update the "length" in vector properties.

Here is the technical request:
Is it possible to provide a parameter that acts as a scaling factor for length? If so, could we also have a scaling factor for angle?

Length: In the singleSlitDiff example, we would like to scale the length by a multiplicative factor. 
(factor) * Length, where factor might be a conversion to "millimeters". The only other small detail would be to allow a unit to be displayed. Length (mm): Value()

Angle: For angle, the factor would almost certainly always be additive, as angles don't typically scale.
(factor) + Angle, where factor might be 20 degrees for the box on an incline example.

Factor would default to 1.0, but there would be parameters in the "html" files that allowed us to set them.

Also, not sure you all realize it, but we are crossing new boundaries with allowing students to directly measure with this tool. Would bring the laboratory online. For the 15th example, this is something we have people do in the lab with rulers. :)

### CODE REVIEW

**Comment by antoviaque** [comment]
@dseaton Nice feature - glad we'll be able to replace the rulers from the lab :p 

Sounds good for the development of this - I'll schedule it for next sprint, along with a review of the examples from the current PR.

**Comment by dseaton** [comment]
@antoviaque One more request. Text labels should have the option to be set to the color of the segment (ruler).

**Comment by antoviaque** [comment]
@dseaton Sounds good.

Btw, for the angle, since it wouldn't be a multiplication, it might make sense to name it differently than "factor" to avoid confusion. If I understood correctly, this would be a value to substract to the angle value currently measured, so this might be better named "base angle"? For example, an angle currently measuring 30 degrees would measure 10 degrees when the "base angle" would be 20 degrees, correct?

**Comment by dseaton** [comment]
@antoviaque Yes, this will be an additive factor. Definitely use addition, that way the user is in control of the negative sign. For the box on an incline example, the user would add "20" to make the x-axis line up with the incline for example.

**Comment by dseaton** [comment]
@antoviaque @mtyaka Here is some urgent feedback.

In working with the segments feature, we are in need of a particular custom check that allows one to measure the relative difference between the midpoints of two segments. I tried to implement this for a couple hours today, but was unable to get to the "segment_coords" using custom_checks.

Two issues:
1. Can @mtyaka try to create a custom check that compares the midpoints of the two curves in example 16? The new curve (SRAS2) should be identical, but shifted down and to the right of the original curve (SRAS1). Note, the coordinate grading already works, but the midpoint custom check would be a more complete grading that would allow more flexible tolerance.

2. The "presence_errmsg" does not seem to be working for "segments". Can this be checked?

As I said, this has a deadline, so would be great if these issues can make it into this week's sprint.

**Comment by mtyaka** [comment]
@dseaton The `presence_errmsg` and `segment_coords_errmsg` weren't working because the python code in `DrawLRAS_S3.xml` was a bit outdated and didn't include support for custom error messages. I updated the python code in the example so that custom error messages work.

I implemented a custom midpoint check and replaced the `segment_coords` check in Example 16 with it (https://github.com/open-craft/jsinput-vectordraw/commit/3e7def7765d88c120a4645a99ae916a92c4750c6). You will probably want to modify the `x,` `y`, and `tolerance` values in `custom_checks: [{check: 'check_sras2_midpoint', x: 1.75, y: -0.25, tolerance: 2.0}]`. You may also want to change the generic error message in https://github.com/open-craft/jsinput-vectordraw/blob/3e7def7765d88c120a4645a99ae916a92c4750c6/Notes_and_Examples/16_DrawRelativeSegment/drawLRAS_S3.xml#L15.

I updated the example at https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/2c6c7bc8a12a4f5e95172c8987b26afa?action=new with latest code - please check and let me know if I need to change the custom check in any way.

The other requested changes (length factor, base angle, and custom label color) will be implemented in a separate pull request.

**Comment by dseaton** [comment]
@mtyaka Thank you! And apologies for the oversight on updating the python code.

I have your code working, and the custom check example is really helpful. I implemented a second custom check that compares the midpoint of the first vector to the second. This allows for a large tolerance with the hand drawn curve, but a firm cutoff that the curve must be shifted down and to the right.

Happy to hear advice on the second custom check.

Thanks for getting to this quickly!

**Comment by mtyaka** [comment]
@dseaton The second custom check looks good, I'll merge this into master.

**Pull request merged**
