### PR TITLE
Visual improvements

### PR DESCRIPTION
**Pull request by e-kolpakov**
Ticket: OC-586
Dependency: https://github.com/open-craft/jsinput-vectordraw/pull/3

Description:

* Vector stats are displayed when creating new vector, dragging existing one, or clicking on vector point/label/line
* Vector tails made non-draggable - allows drawing multiple vectors from same point
* Background image ratio can be preserved - omit height in background specification
* Vector styling (rigid variant - only allowed options are applied)

### CODE REVIEW

**Comment by Kelketek** [comment]
Took a good long while to verify this all, but it does appear to work. :+1:

**Comment by dseaton** [comment]
Great - I think there has also been progress by @mtyaka.

**Comment by antoviaque** [comment]
@dseaton Yup - once @mtyaka has updated the edge course, tested and merged #1, this would be rebased. Maybe it would be worth giving access to @e-kolpakov to edge too, so he can also update edge? @e-kolpakov what's your account email on edge?

**Comment by e-kolpakov** [comment]
@antoviaque it is eugeny@opencraft.com. I have changed it recently.

**Comment by antoviaque** [comment]
@e-kolpakov Thanks! @dseaton can you give access to @e-kolpakov ?

Actually @e-kolpakov if you get access before Matjaz updates it there, you could rebase now against his branch and put both on edge for testing at the same time.

**Comment by e-kolpakov** [comment]
@antoviaque @dseaton just in case, I've just double checked an it appears email was not changed. So, correct email is eugeny.kolpakov@gmail.com.

**Comment by dseaton** [comment]
@e-kolpakov You have been added to the course.

https://studio.edge.edx.org/course/DavidsonNext/Ann101/3T2014

**Comment by e-kolpakov** [comment]
@dseaton thank you. I've got other stuff to do for now, so I'm not sure if I'll be able to update sandbox today - I'll let you know if I do.

**Comment by dseaton** [comment]
@e-kolpakov Sure - thanks!

**Comment by e-kolpakov** [comment]
@dseaton I've just updated sandbox with contents of this PR (+ #3).

It showcases:

* Non-draggable vector origins: allows drawing a vector on top of other vector's origin. If origin needs to be moved entire vector needs to be dragged.
* Interactive vector properties block: vector properties are updated when vector is selected (clicking on arrow or any of points) or modified (drawed or dragged).
* Better background image handling: if both width and height are specified it is assumed course author knows what is (s)he doing and background is stretched to match specified dimensions. If only width is specified, height is automatically calculated using actual image width/height ratio.
* Vector styling - N and f vectors are restyled (color/width/label), g has default style.
* All the features included in #3

**Comment by dseaton** [comment]
@e-kolpakov Great regarding bullet 1, 2, 3.  Bullet 4 - I'll play around with these features later today. Thanks for putting up a couple versions.

@mtyaka Please let me know if there is anything I need to consider here.

**Comment by mtyaka** [comment]
@dseaton This includes the font size tweaks from #3, so please check whether the font sizes and vector widths look better now.

**Comment by dseaton** [comment]
@mtyaka @e-kolpakov Apologies, but can one of you update the vectordraw.js and vectordraw.css files in the course again? 

I was trying to add a simple fix without asking you all - add "showNavigation:false" to the default_settings in VectorDraw.

Fonts/Vector Size all looked good this morning, but I will give some feedback once things are updated in Studio. Sorry again.

Also note, I was working on three prototype problems that are desired in our Physics course:
https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/508d02e23a1e4d2bab6c00643424f228

I'll fix these once the latest code is up. We can actually get this merge done, then worry about the examples.

**Comment by e-kolpakov** [comment]
@dseaton ok, I'll upload it now

**Comment by dseaton** [comment]
Default Font-Size:  Good for both dropdown and vector labels
Default Vector StrokeWidth:  Good
Vector Properties:  Good

Additional Fixes:
1. Add "showNavigation: false" to the "default_settings" in vectordraw.js.
This will remove the zoom controls in the bottom right corner.
2. Is it possible to make the drawing canvas slightly larger?  W = 550 and
H = 400. Note, if this overflows within "edge" or "edX", not worth it.
Regardless I would make height 400 to balance out the size.

Issues:
1. All images still seem somewhat stretched to me. SimpleCar.png has a lot
of white space at the top and bottom, which makes it compress in the
y-direction. See all my prototypes for other examples.
2. Background images start at the bottom of the screen. Would it be better
to have images centered relative to the JSXgraph box?

@e-kolpakov I think you were working on the background image - is there
still room to improve the management of background images?


Also, the tool is looking really great! Our pilot teachers, content
editors, and soon to be students, are going to really like this tool!

**Comment by dseaton** [comment]
@e-kolpakov Thanks regarding font awesome. I was using outdated code all around. Once we merge, I'll fix all those examples.

Fine with me if you all want to merge now, and address those additional comments in a different PR.

**Comment by e-kolpakov** [comment]
@dseaton 

* showNavigation - set to false by default. To override, set `show_navigation` to true in top level config (`api-example.html`)
* width/height - it is possible to set it up manually (updated api-example.html to showcase that). Default values set to 550 and 400 as requested
* Image distortions were caused by incorrect graph bounding box - it was square, while viewport was rectangle - graph evenly distorted everything (including vectors) to stick bounding box sides to viewport. Now bounding box is calculated automatically from viewport width/height. As a side effect, it's now only possible to specify bounding box scale (a plain number) - visible graph part will be bounded between `[-scale; scale]` vertically and `[-scale*ratio; scale*ratio]`, where `ratio` is viewport width/height ratio.
* If image coords is not specified it is centered with graph (showcased in new api-example.html).

Also, I've updated api-example.xml - set width = 800 to accomodate for graph width increase. It looks good in studio and LMS, but if you have any scrolls appearing (or graph menu being pushed below graph) - please try to adjust widths/heights in api-example.xml and api-example.html

**Comment by e-kolpakov** [comment]
@dseaton I'm merging this PR, if you have any further feedback or requests we'll handle them in a separate PR.

**Comment by dseaton** [comment]
@e-kolpakov Thanks!

**Pull request merged**
