### PR TITLE
Bug fixes for lines and points

### PR DESCRIPTION
**Pull request by smarnach**
Fix a few issues found in #23.

### CODE REVIEW

**Comment by bdero** [comment]
I tested this in firefox, confirming that I was unable to draw the line/point with master, and was able to successfully do so with this branch. :+1: 

Before (Firefox):


After (Firefox):


Note: The center-of-mass point is placed incorrectly in Firefox and correct in Chromium, but this is an unrelated problem that exists both before and after this change.

Here's what it looks like in Chromium:

**Comment by bdero** [comment]
@smarnach What exactly are the changes in https://github.com/open-craft/jsinput-vectordraw/pull/24/commits/a1cd5becf611ec7059f8a2163a9b2312dbe10b89 fixing? Just the change in https://github.com/open-craft/jsinput-vectordraw/pull/24/commits/33c1d0cf53806b5fa67b290293af2f8e5b53a1e9 seems to fix the clicking to draw problem mentioned in #23 .

**Comment by smarnach** [comment]
@bdero With the old code, all vectors and points end up with the same object in the `style` attribute (unless it's explicitly overwritten by the configuration).  Since the object is shared among all of them, modifications of the object will affect all points or vectors, which is not intended.

**Comment by bdero** [comment]
@smarnach Ah, that makes sense, that must be why I was seeing some minor style differences with this change as well. This looks good to me. :+1:

**Comment by bdero** [comment]
When I wrote my prior comments I had forgotten about the official template, so here goes:

:+1:

- [x] I tested this:  tested this in firefox, confirming that I was unable to draw the line/point with master, and was able to successfully do so with this branch.
- [x] I read through the code
- [ ] ~~Includes documentation~~ This change does not require documentation.

**Pull request merged**
