### PR TITLE
Notes, Examples, and a couple issues

### PR DESCRIPTION
**Pull request by dseaton**
@antoviaque I went through the process of finalizing 4 prototype vector problems. The latest - an "energy levels" problem - brings up a few issues described below and in my notes. The purpose of these examples was to give us all a bench mark on problem creation and the issues that might arise.

This pull request provides the following:
1. 4 example vector drawing problems: protractor, box on incline, flight path, and energy levels
2. Notes on the process of creating the "energy-levels" problem.
3. Questions/Issues about the process of creating a problem.

The pull request itself only adds examples and notes. There are no updates to the code base.

Particular Issues:
1. What is the utility of "points" in the HTML file? I use them to figure out where the tail of a vector should go, but then I hide them off screen. Are they important for grading? Should we allow "points" to be commented out once a problem is finished?

2. Turn off highlighting of text labels. Mouse drawn vectors will not initiate if over a text label.

3.  Turn off info box that shows JSXgraph coordinates on rollover. Use this one liner in default settings. liner:https://github.com/DavidsonNext/Interactives/blob/master/Macroeconomics/JS/Macro.js#L2

Questions/Documentation:
1. The "energy-levels" problem is a good example of a problem whose vectors do not need labels. Can we currently grade setups with unlabeled vectors? Note, my current example tries to create labeled vectors. 

2. Is it possible to grade the tail location of a vector for only one coordinate? In the case of the "energy levels" problem, we only need grade based on the y location. 

Also, I showed the vector drawing tool to our content editors, and they were very impressed. They send their collective thanks!

### CODE REVIEW

**Comment by antoviaque** [comment]
@dseaton Thanks for this! A review of the exercises will be included in the upcoming sprint, as well as addressing the issues you pointed out.

For your question about points, they aren't important for grading no - they can simply be hidden if you don't have a use for them, it's true that they can make drawing vectors more difficult. It makes more sense to include this on the background image imho.

**Comment by dseaton** [comment]
@antoviaque Leave points for now. They were the only way I could identify the tail locations for the vectors - these have to be JSXgraph coordinates.

Points on the background image are good, but have a lot of pedagogical issues. For example, if I drew points on the energy levels diagram, students would immediately know the answers. For the box on incline, a point on the background image would be fine.

**Comment by antoviaque** [comment]
@dseaton Sounds good

**Comment by mtyaka** [comment]
@dseaton The examples look great. I made some small updates to the examples in https://github.com/open-craft/jsinput-vectordraw/pull/7, please have a look.

As mentioned in that pull request, `points` are not important for grading and you can safely remove them. The reason why your example didn't work was that it was using outdated grading code.

**Pull request merged**
