### PR TITLE
Using "python_lib.zip" to scale grading code and AWS for storing JS/CSS

### PR DESCRIPTION
**Pull request by dseaton**
@mtyaka @antoviaque @e-kolpakov @smarnach 
This pull request is meant to incorporate more examples, but specifically, to show a method for storing python grading code in a given course.

**python_lib.zip**
"python_lib.zip" is a known search term for edX problem types. Any python libraries within that zip folder can be uploaded and referenced via the custom python grader. To create the file, one simply needs to run the following:
```
zip -r python_lib.zip python_lib/*
```

See example 18 [link](https://github.com/open-craft/jsinput-vectordraw/tree/Daniel/Notes_and_Examples/18_Draw_LongRunEquil), I have removed all Python-API code and simply imported it via "import vectordraw.py". This allows us to make changes to one file and update the base grading code by uploading the "python_lib.zip" file directly to studio.

**Note, number 18 currently throws an error when grading.**

I can't officially get this problem graded. What piece of the grading code should remain in a given problem? And what could simply be imported? Here is a studio link:
https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/d3dfcf7a44ed48f486a1d30bf3a5efa8

**Hosting on AWS**
Also note, I am hosting a lot of interactive content on AWS. I'll likely reference vectordraw.js and vectordraw.css from there. You can see the use of AWS in example 20. Here is an example link:
https://dnextinteractives.s3.amazonaws.com/Physics/JS/vectordraw.js

Should be a simple merge, but can we talk about how the python_lib.zip might impact our workflow?

### CODE REVIEW

**Comment by antoviaque** [comment]
@dseaton Thank you for the PR, especially the python_lib trick - it definitely looks like a good way to package the shared code. I'll include a review of the exercises and having a closer look at the python_lib.zip approach in the next sprint.

**Comment by mtyaka** [comment]
@dseaton Thanks for the info about python_lib.zip, it makes a lot of sense to use that in our case so that we don't have to repeat the code in every problem XML file.

The issue with example 18 on edge was that when using the zip file, you need to set the `cfn` parameter to `vectordraw.vglcfn` instead of just `vglcfn`. I made that change on edge and the grading now works as expected.

Note that with python_lib.zip, there are also some small differences in how to define custom grading functions. I updated `api-example.xml` and all examples to use `python_lib.zip`.

I also added a `python_lib.zip` to the root of this file that we will try to keep updated as we make changes to `vectordraw.py`.

This simplifies the grading code and gave me inspiration to try and see if it would be possible to use the same boilerplate html file for all exercises and define the vector parameters and settings directly in the problem editor in the studio since having to make changes to the html file and keep reuploading it while you're working on an exercise can be quite tedious. It looks like it would be possible, but requires some more time to look into. If you're interested, we could schedule some time to do that during one of the next sprints.

@bradenmacdonald Can you please check the commits I added to this PR?

**Comment by dseaton** [comment]
@mtyaka @antoviaque Great that "python_lib" is working. Note, I am generally happy with this solution, but must also note that I have ~ 20 vector drawing problems already in production for our courses. Rather than fixing those, can we simply move forward in such a way that all my new creation will use the "python_lib" version?

And thank you for clarifying vectordraw.vglcfn - trying to get courses out has a certain way of deadening the brain to such fixes. :)

Also, glad you are inspired. I would highly recommend working on the "in studio" authoring of the problem. Something similar was done by @smarnach for the Active Table problem type we have. My feeling is that this will better prepare us for generalized authoring, and it will allow us to train others on this version of the problem type.

Forgot to mention to you all, at a conference last month I displayed these tools. I'd say there were roughly 5 course teams who were very eager to investigate the tools. Great work!

@antoviaque @mtyaka Let me know the hours you will need. We have budget, and it will be impactful if we can get this started quickly.

**Comment by antoviaque** [comment]
@dseaton Great to hear! Glad the tools are interesting for course teams : )

For the changes @mtyaka was mentioning, he's on holidays this week so I can't confirm the timescale with him, but my impression is that it wouldn't be too big of a change, likely not more than 1-2 days. There are a few items on our plate that we need to complete before I can schedule it though, so that leaves time for Matjaz to come back next week and then for you to confirm. Would that work for you?

**Comment by bradenmacdonald** [comment]
@mtyaka Make sure you are aware of the potential issue that I pointed out. Otherwise :+1: from me on your commits.

**Pull request merged**
